replicaCount: 1

image:
  repository: shiftedreality/magento-kubernetes-components-php
  tag: 7.1-fpm
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 80
  nodePort: 30102

persistence:
  nfs:
    enabled: false

checkout:
    name: magento2-checkout
    service:
      type: NodePort
      ports:
        nodePort: 30102
        port: 80
    deployment:
      nginxImage: nginx:1.9
      codeImage: shiftedreality/magento-kubernetes-components-php
      imageTag: 7.1-fpm
      imagePullPolicy: Always
global:
  checkout:
    volumeHostPath: /Users/admin/Projects/charts/checkout/sources

resources: {}
  # Uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

global:
  chekout:
    mysqlHost: checkout-mysql

checkout-mysql:
  initializationFiles:
    first-db.sql: |-
        CREATE DATABASE IF NOT EXISTS checkout DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
